### ISSUE TITLE
Could you write an example

### ISSUE THREAD

**Issue by gaoyuanzong** [sinri/Keel#6]
Could you write an example

**Comment by sinri** [comment]
Well, a good idea, would be handled if I have any free time.
Truely the functions are out of human memory.

If you mean a quick-start for project, the following may help. 
https://github.com/sinri/DryDockOfKeel

**Comment by sinri** [comment]
I started a project to provide lession around how to startup with DryDock, including Keel.
Ref: https://github.com/sinri/DryDockLession
